### ISSUE TITLE
Python 3.12.0rc1 is released: Release a new version with 3.12 support?

### ISSUE THREAD

**Issue by hwalinga** [contourpy/contourpy#262] opened 2023-08-18 13:28 UTC
Since the first release candidate for Python 3.12 was released yesterday. Maybe it is time to make a new release on Python that officially supports 3.12? 

Thanks a lot!

**Comment by ianthomas23** [comment] 2023-08-18 13:47
There won't be any release here until NumPy have an official release on PyPI that supports Python 3.12. This is in progress https://pypi.org/project/numpy/1.26.0b1/#files

**Comment by effigies** [comment] 2023-08-25 16:31
Would you consider pushing a beta, similar to numpy's 1.26.0b1, so that matplotlib can start shipping [nightly wheels](https://anaconda.org/scientific-python-nightly-wheels/matplotlib/files) for cp312 and downstream tools can run their full test suites? Or even a `.dev0` that could be yanked later?

I don't have stats, but matplotlib is likely to be a blocker for a large number of projects in the scientific python ecosystem., and it would be nice to identify regressions in Python 3.12 before its final release.

**Comment by ianthomas23** [comment] 2023-08-25 19:44
@effigies It is a reasonable request, but you don't need a ContourPy `dev` wheel as the latest sdist suffices.

ContourPy has been built and tested on python 3.12 for over 2 months now (#254) on the major 3 platforms. There hasn't been a single problem identified caused by switching from 3.11 to 3.12. Incidentally, those CI runs necessitate building NumPy from source, which I have been happy to do to obtain early information about python 3.12 compatibility. Matplotlib's equivalent PR (matplotlib/matplotlib#24711) has yet to be merged so downstream projects are much more likely to have a problem with Matplotlib than ContourPy.

Neither your projects nor Matplotlib need to wait for a ContourPy release that supports python 3.12 before you can proceed. There is no blocker here. Building ContourPy 1.1.0 from sdist takes about a minute on the 3 major platforms (e.g.  https://github.com/contourpy/contourpy/actions/runs/5914819149/job/16040481410) using the usual `pip install` command assuming you have an appropriate toolchain installed which is always the case on github actions.

**Comment by ianthomas23** [comment] 2023-09-09 13:52
There is now a ContourPy release candidate `1.1.1rc1` available (https://github.com/contourpy/contourpy/releases/tag/v1.1.1rc1) which includes wheels for Python 3.12.

To install from PyPI use
```bash
pip install --pre contourpy
```
or the more explicit
```bash
pip install "contourpy==1.1.1rc1"
```

**Comment by ianthomas23** [comment] 2023-09-17 16:57
ContourPy 1.1.1 is available on PyPI and conda-forge including wheels for CPython 3.12.

**Closed by ianthomas23** 2023-09-17 16:57 UTC
